# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mickey/Documents/projects/CLion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mickey/Documents/projects/CLion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

manual:
	@./build.sh

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mickey/Documents/projects/CLion/CMakeFiles /home/mickey/Documents/projects/CLion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mickey/Documents/projects/CLion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mellow

# Build rule for target.
mellow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mellow
.PHONY : mellow

# fast build rule for target.
mellow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/build
.PHONY : mellow/fast

src/dispresults.o: src/dispresults.c.o
.PHONY : src/dispresults.o

# target to build an object file
src/dispresults.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/dispresults.c.o
.PHONY : src/dispresults.c.o

src/dispresults.i: src/dispresults.c.i
.PHONY : src/dispresults.i

# target to preprocess a source file
src/dispresults.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/dispresults.c.i
.PHONY : src/dispresults.c.i

src/dispresults.s: src/dispresults.c.s
.PHONY : src/dispresults.s

# target to generate assembly for a file
src/dispresults.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/dispresults.c.s
.PHONY : src/dispresults.c.s

src/files.o: src/files.cpp.o
.PHONY : src/files.o

# target to build an object file
src/files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/files.cpp.o
.PHONY : src/files.cpp.o

src/files.i: src/files.cpp.i
.PHONY : src/files.i

# target to preprocess a source file
src/files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/files.cpp.i
.PHONY : src/files.cpp.i

src/files.s: src/files.cpp.s
.PHONY : src/files.s

# target to generate assembly for a file
src/files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/files.cpp.s
.PHONY : src/files.cpp.s

src/git/clone.o: src/git/clone.c.o
.PHONY : src/git/clone.o

# target to build an object file
src/git/clone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/git/clone.c.o
.PHONY : src/git/clone.c.o

src/git/clone.i: src/git/clone.c.i
.PHONY : src/git/clone.i

# target to preprocess a source file
src/git/clone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/git/clone.c.i
.PHONY : src/git/clone.c.i

src/git/clone.s: src/git/clone.c.s
.PHONY : src/git/clone.s

# target to generate assembly for a file
src/git/clone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/git/clone.c.s
.PHONY : src/git/clone.c.s

src/json/filtrejson.o: src/json/filtrejson.c.o
.PHONY : src/json/filtrejson.o

# target to build an object file
src/json/filtrejson.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/filtrejson.c.o
.PHONY : src/json/filtrejson.c.o

src/json/filtrejson.i: src/json/filtrejson.c.i
.PHONY : src/json/filtrejson.i

# target to preprocess a source file
src/json/filtrejson.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/filtrejson.c.i
.PHONY : src/json/filtrejson.c.i

src/json/filtrejson.s: src/json/filtrejson.c.s
.PHONY : src/json/filtrejson.s

# target to generate assembly for a file
src/json/filtrejson.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/filtrejson.c.s
.PHONY : src/json/filtrejson.c.s

src/json/formatjson.o: src/json/formatjson.c.o
.PHONY : src/json/formatjson.o

# target to build an object file
src/json/formatjson.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/formatjson.c.o
.PHONY : src/json/formatjson.c.o

src/json/formatjson.i: src/json/formatjson.c.i
.PHONY : src/json/formatjson.i

# target to preprocess a source file
src/json/formatjson.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/formatjson.c.i
.PHONY : src/json/formatjson.c.i

src/json/formatjson.s: src/json/formatjson.c.s
.PHONY : src/json/formatjson.s

# target to generate assembly for a file
src/json/formatjson.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/formatjson.c.s
.PHONY : src/json/formatjson.c.s

src/json/getdata.o: src/json/getdata.c.o
.PHONY : src/json/getdata.o

# target to build an object file
src/json/getdata.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/getdata.c.o
.PHONY : src/json/getdata.c.o

src/json/getdata.i: src/json/getdata.c.i
.PHONY : src/json/getdata.i

# target to preprocess a source file
src/json/getdata.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/getdata.c.i
.PHONY : src/json/getdata.c.i

src/json/getdata.s: src/json/getdata.c.s
.PHONY : src/json/getdata.s

# target to generate assembly for a file
src/json/getdata.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/getdata.c.s
.PHONY : src/json/getdata.c.s

src/json/prettyprint.o: src/json/prettyprint.c.o
.PHONY : src/json/prettyprint.o

# target to build an object file
src/json/prettyprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/prettyprint.c.o
.PHONY : src/json/prettyprint.c.o

src/json/prettyprint.i: src/json/prettyprint.c.i
.PHONY : src/json/prettyprint.i

# target to preprocess a source file
src/json/prettyprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/prettyprint.c.i
.PHONY : src/json/prettyprint.c.i

src/json/prettyprint.s: src/json/prettyprint.c.s
.PHONY : src/json/prettyprint.s

# target to generate assembly for a file
src/json/prettyprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/json/prettyprint.c.s
.PHONY : src/json/prettyprint.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/main.c.s
.PHONY : src/main.c.s

src/scripts/build.o: src/scripts/build.c.o
.PHONY : src/scripts/build.o

# target to build an object file
src/scripts/build.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/build.c.o
.PHONY : src/scripts/build.c.o

src/scripts/build.i: src/scripts/build.c.i
.PHONY : src/scripts/build.i

# target to preprocess a source file
src/scripts/build.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/build.c.i
.PHONY : src/scripts/build.c.i

src/scripts/build.s: src/scripts/build.c.s
.PHONY : src/scripts/build.s

# target to generate assembly for a file
src/scripts/build.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/build.c.s
.PHONY : src/scripts/build.c.s

src/scripts/rmdeps.o: src/scripts/rmdeps.c.o
.PHONY : src/scripts/rmdeps.o

# target to build an object file
src/scripts/rmdeps.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmdeps.c.o
.PHONY : src/scripts/rmdeps.c.o

src/scripts/rmdeps.i: src/scripts/rmdeps.c.i
.PHONY : src/scripts/rmdeps.i

# target to preprocess a source file
src/scripts/rmdeps.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmdeps.c.i
.PHONY : src/scripts/rmdeps.c.i

src/scripts/rmdeps.s: src/scripts/rmdeps.c.s
.PHONY : src/scripts/rmdeps.s

# target to generate assembly for a file
src/scripts/rmdeps.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmdeps.c.s
.PHONY : src/scripts/rmdeps.c.s

src/scripts/rmpkgs.o: src/scripts/rmpkgs.c.o
.PHONY : src/scripts/rmpkgs.o

# target to build an object file
src/scripts/rmpkgs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmpkgs.c.o
.PHONY : src/scripts/rmpkgs.c.o

src/scripts/rmpkgs.i: src/scripts/rmpkgs.c.i
.PHONY : src/scripts/rmpkgs.i

# target to preprocess a source file
src/scripts/rmpkgs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmpkgs.c.i
.PHONY : src/scripts/rmpkgs.c.i

src/scripts/rmpkgs.s: src/scripts/rmpkgs.c.s
.PHONY : src/scripts/rmpkgs.s

# target to generate assembly for a file
src/scripts/rmpkgs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/rmpkgs.c.s
.PHONY : src/scripts/rmpkgs.c.s

src/scripts/uninstall.o: src/scripts/uninstall.c.o
.PHONY : src/scripts/uninstall.o

# target to build an object file
src/scripts/uninstall.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/uninstall.c.o
.PHONY : src/scripts/uninstall.c.o

src/scripts/uninstall.i: src/scripts/uninstall.c.i
.PHONY : src/scripts/uninstall.i

# target to preprocess a source file
src/scripts/uninstall.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/uninstall.c.i
.PHONY : src/scripts/uninstall.c.i

src/scripts/uninstall.s: src/scripts/uninstall.c.s
.PHONY : src/scripts/uninstall.s

# target to generate assembly for a file
src/scripts/uninstall.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/scripts/uninstall.c.s
.PHONY : src/scripts/uninstall.c.s

src/splitfiles.o: src/splitfiles.c.o
.PHONY : src/splitfiles.o

# target to build an object file
src/splitfiles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/splitfiles.c.o
.PHONY : src/splitfiles.c.o

src/splitfiles.i: src/splitfiles.c.i
.PHONY : src/splitfiles.i

# target to preprocess a source file
src/splitfiles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/splitfiles.c.i
.PHONY : src/splitfiles.c.i

src/splitfiles.s: src/splitfiles.c.s
.PHONY : src/splitfiles.s

# target to generate assembly for a file
src/splitfiles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/splitfiles.c.s
.PHONY : src/splitfiles.c.s

src/web/getpkg.o: src/web/getpkg.c.o
.PHONY : src/web/getpkg.o

# target to build an object file
src/web/getpkg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/getpkg.c.o
.PHONY : src/web/getpkg.c.o

src/web/getpkg.i: src/web/getpkg.c.i
.PHONY : src/web/getpkg.i

# target to preprocess a source file
src/web/getpkg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/getpkg.c.i
.PHONY : src/web/getpkg.c.i

src/web/getpkg.s: src/web/getpkg.c.s
.PHONY : src/web/getpkg.s

# target to generate assembly for a file
src/web/getpkg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/getpkg.c.s
.PHONY : src/web/getpkg.c.s

src/web/scraper.o: src/web/scraper.c.o
.PHONY : src/web/scraper.o

# target to build an object file
src/web/scraper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/scraper.c.o
.PHONY : src/web/scraper.c.o

src/web/scraper.i: src/web/scraper.c.i
.PHONY : src/web/scraper.i

# target to preprocess a source file
src/web/scraper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/scraper.c.i
.PHONY : src/web/scraper.c.i

src/web/scraper.s: src/web/scraper.c.s
.PHONY : src/web/scraper.s

# target to generate assembly for a file
src/web/scraper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mellow.dir/build.make CMakeFiles/mellow.dir/src/web/scraper.c.s
.PHONY : src/web/scraper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mellow"
	@echo "... src/dispresults.o"
	@echo "... src/dispresults.i"
	@echo "... src/dispresults.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/git/clone.o"
	@echo "... src/git/clone.i"
	@echo "... src/git/clone.s"
	@echo "... src/json/filtrejson.o"
	@echo "... src/json/filtrejson.i"
	@echo "... src/json/filtrejson.s"
	@echo "... src/json/formatjson.o"
	@echo "... src/json/formatjson.i"
	@echo "... src/json/formatjson.s"
	@echo "... src/json/getdata.o"
	@echo "... src/json/getdata.i"
	@echo "... src/json/getdata.s"
	@echo "... src/json/prettyprint.o"
	@echo "... src/json/prettyprint.i"
	@echo "... src/json/prettyprint.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scripts/build.o"
	@echo "... src/scripts/build.i"
	@echo "... src/scripts/build.s"
	@echo "... src/scripts/rmdeps.o"
	@echo "... src/scripts/rmdeps.i"
	@echo "... src/scripts/rmdeps.s"
	@echo "... src/scripts/rmpkgs.o"
	@echo "... src/scripts/rmpkgs.i"
	@echo "... src/scripts/rmpkgs.s"
	@echo "... src/scripts/uninstall.o"
	@echo "... src/scripts/uninstall.i"
	@echo "... src/scripts/uninstall.s"
	@echo "... src/splitfiles.o"
	@echo "... src/splitfiles.i"
	@echo "... src/splitfiles.s"
	@echo "... src/web/getpkg.o"
	@echo "... src/web/getpkg.i"
	@echo "... src/web/getpkg.s"
	@echo "... src/web/scraper.o"
	@echo "... src/web/scraper.i"
	@echo "... src/web/scraper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

