#ifndef WGET_H
    #define WGET_H
#endif

const static char WgetSh[] = 
    "#!/bin/bash\n\n"
    "exists()\n"
    "{\n"
    "    command -v \"$1\" > /dev/null 2 >& 1\n"
    "}\n\n"
    "if exists wget; then\n"
    "    echo 'wget is already installed'\n"
    "    exit 0\n"
    "fi\n\n"
    "if exists apt-get; then\n"
    "    # Debian\n"
    "    sudo apt-get update\n"
    "    sudo apt-get install -y wget\n\n"
    "elif exists yum; then\n"
    "    # Redhat\n"
    "    sudo yum install -y wget\n\n"
    "elif exists pacman; then\n"
    "    # Archlinux\n"
    "    sudo pacman -Sy --noconfirm wget\n\n"
    "elif exists apk; then\n"
    "    # Alpine\n"
    "    sudo apk add --update wget\n\n"
    "elif exists dnf; then\n"
    "    # Fedora\n"
    "    sudo dnf install -y wget\n\n"
    "elif exists zypper; then\n"
    "    # Opensussy\n"
    "    sudo zypper install -y wget\n\n"
    "elif exists brew; then\n"
    "    # MacOS\n"
    "    brew install wget\n\n"
    "elif exists port; then\n"
    "    # MacOS\n"
    "    sudo port install wget\n\n"
    "elif exists pkg; then\n"
    "    # FreeBSD\n"
    "    sudo pkg install -y wget\n\n"
    "elif exists emerge; then\n"
    "    # Gentoo\n"
    "    sudo emerge --ask --noreplace wget\n\n"
    "elif exists eopkg; then\n"
    "    # Solus\n"
    "    sudo eopkg install -y wget\n\n"
    "elif exists guix; then\n"
    "    # Guix\n"
    "    sudo guix package -i wget\n\n"
    "else\n"
    "    echo 'Unsupported package manager, install wget manually'\n"
    "    exit 1\n"
    "fi\n\n"
    "if exists wget; then\n"
    "    echo 'wget was successfully installed'\n"
    "    exit 0\n"
    "else\n"
    "    echo 'There was an error, please install wget manually'\n"
    "    exit 1\n"
    "fi\n";

//const static char WgetBat[] = "";

